# Project: Project4
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main2.o
LINKOBJ  = main2.o
LIBS     = -L"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/burak/Desktop/VeloxOS/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Project4.exe
CXXFLAGS = $(CXXINCS) -std=c++17
CFLAGS   = $(INCS) -std=c++17
DEL      = C:\Users\burak\Desktop\VeloxOS\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main2.o: main2.cpp
	$(CPP) -c main2.cpp -o main2.o $(CXXFLAGS)
